# Copyright (C) 2023 TomTom NV. All rights reserved.


name: Publish TechDocs Site

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  id-token: write
  contents: read

env:
  ENTITY_NAMESPACE: default
  ENTITY_KIND: "Component"
  ENTITY_NAME: integrate-zendesk-saprefund

jobs:
  publish-techdocs-site:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish Techdocs
        uses: tomtom-internal/sp-idp-techdocs-publisher@v1.1.0
        with:
          kind: ${{ env.ENTITY_KIND }}
          namespace: ${{ env.ENTITY_NAMESPACE }}
          entityName: ${{ env.ENTITY_NAME }}
